### ISSUE TITLE
Tidy up / simplify README.md

### ISSUE THREAD

**Issue by stefanmiodrag** [stefanmiodrag/stefanmiodrag.com#6]
This is a good first issue for someone who'd like to participate in the Hacktoberfest. I quickly created the README.md file but it could use some love 💙 Feel free to do a pull request.

**Comment by XOptimistixX** [comment]
Hi, I would like to have a go at this issue.

**Comment by stefanmiodrag** [comment]
@XOptimistixX Sure! Go ahead 👍 Let me know if you have any questions.
