### ISSUE TITLE
Replace .gif with gradient that changes color smoothly.

### ISSUE THREAD

**Issue by stefanmiodrag** [stefanmiodrag/stefanmiodrag.com#7]
At the moment, the site is using a .gif that repeats. Due to this, it cuts off quite strangely. If anyone would like to take a look at it and potentially replace it with a gradient that changes color over time.

**Comment by collinsnji** [comment]
Hi @stefanmiodrag I'll like to work on this

**Comment by stefanmiodrag** [comment]
@collinsnji Awesome. Thank you! Appreciate it 💙 Let me know if you have any questions.

**Comment by collinsnji** [comment]
Are you OK with me using a CSS gradient + some Material Design Palette colours?

**Comment by stefanmiodrag** [comment]
Sure, that sounds fine 😄

**Comment by collinsnji** [comment]
@stefanmiodrag I made a PR :)

**Comment by stefanmiodrag** [comment]
@collinsnji Awesome! It looks great, thanks a bunch 😸 ❤️
