### ISSUE TITLE
Hacktoberfest! 🎉 Help with copy(writing) for personal site.

### ISSUE THREAD

**Issue by stefanmiodrag** [stefanmiodrag/stefanmiodrag.com#8]
Hey, I wrote the copy myself for the site. If anyone feels like there's something that could be changed / updated. Feel free to do a pull request! 💙

**Comment by mdt2** [comment]
I'll work on a few tweaks for this. I only see some small changes that will improve UX.

**Comment by stefanmiodrag** [comment]
Hey @mdt2, thank you for taking the time to look at it. I'll probably not keep the italic on the <p> tags though. Otherwise, thanks! 👍 😸
